global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /metrics

  - job_name: 'image-svc'
    static_configs:
      - targets: ['image-svc:50051']
    metrics_path: /metrics

  - job_name: 'facts-svc'
    static_configs:
      - targets: ['facts-svc:50052']
    metrics_path: /metrics

  - job_name: 'worker-svc'
    static_configs:
      - targets: ['worker-svc:50053']
    metrics_path: /metrics

  - job_name: 'nsq'
    static_configs:
      - targets: ['nsqd:4151']
    metrics_path: /stats
    params:
      format: ['prometheus']
